# Generated by Django 4.2.16 on 2024-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0002_remove_song_artist_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='game_stuff_images')),
            ],
        ),
    ]
