# Generated by Django 4.2.16 on 2024-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0004_gamestuff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestuff',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
