# Generated by Django 4.2.16 on 2024-11-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0005_alter_gamestuff_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestuff',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gamestuff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gamestuff',
            name='name',
        ),
        migrations.AddField(
            model_name='gamestuff',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='game_stuff_videos'),
        ),
    ]
