# Generated by Django 4.2.16 on 2024-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0007_gamestuff_description_gamestuff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_backgrounds'),
        ),
        migrations.AddField(
            model_name='sekaiworld',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='sekai_backgrounds'),
        ),
    ]
