# Generated by Django 4.2.16 on 2024-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0008_group_background_image_sekaiworld_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_backgrounds'),
        ),
    ]
