# Generated by Django 4.2.16 on 2024-11-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0010_sekaiitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekaiitems',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sekai_app.character'),
        ),
    ]
