# Generated by Django 4.2.16 on 2024-11-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0011_sekaiitems_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sekai_app.character'),
        ),
    ]
