# Generated by Django 4.2.16 on 2024-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0012_event_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='character',
        ),
        migrations.AddField(
            model_name='event',
            name='character',
            field=models.ManyToManyField(blank=True, related_name='events', to='sekai_app.character'),
        ),
    ]
