# Generated by Django 4.2.16 on 2024-11-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0013_remove_event_character_event_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='character_cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='sekai_app.card'),
        ),
    ]
