# Generated by Django 4.2.16 on 2024-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekai_app', '0014_event_character_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='character_cards',
            field=models.ManyToManyField(blank=True, related_name='events', to='sekai_app.card'),
        ),
    ]
